service: dataeng-team-futures-wh-process

package:
  individually: true

provider:
  name: aws
  runtime: python3.7
  tracing:
    lambda: true
  environment:
    TEAM_HANDLER: src/handler/process_team_futures.process_team_futures
    BOOKID: 'wh:book:whnj'
    BUCKET: 'dataeng-futures-wh-${opt:stage, self:provider.stage}'
    DOC_DB_CONNECTION_STRING:  ${file(./config/config-${opt:stage, self:provider.stage}.yml):docDbConnectionString}
    LEAGUE_MONGO_COLLECTION: 'league_team_futures_wh'
    TEAM_MONGO_COLLECTION: 'team_futures_wh'
    PYMONGO_LAYER: ${file(./config/config-${opt:stage, self:provider.stage}.yml):pymongo-layer}
  stage: ${opt:stage, 'qa'}
  region: us-east-1
  timeout: 60
  vpc: ${file(./config/config-${opt:stage, self:provider.stage}.yml):vpc}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:provider.environment.BUCKET}/*'

functions:
  # NFL
  nfl_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nfl'
        CBS_LEAGUE_ID: 59
        MARKET_NAMES: ${file(./config/config-nfl.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NBA
  nba_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nba'
        CBS_LEAGUE_ID: 54
        MARKET_NAMES: ${file(./config/config-nba.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # MLB
  mlb_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'mlb'
        CBS_LEAGUE_ID: 52
        MARKET_NAMES: ${file(./config/config-mlb.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NCAAF
  ncaaf_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'ncaaf'
        CBS_LEAGUE_ID: 56
        MARKET_NAMES: ${file(./config/config-ncaaf.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NCAAB
  ncaab_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'ncaab'
        CBS_LEAGUE_ID: 55
        MARKET_NAMES: ${file(./config/config-ncaab.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # nhl
  nhl_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nhl'
        CBS_LEAGUE_ID: 60
        MARKET_NAMES: ${file(./config/config-nhl.json):market_names}
    events:
      - s3: ${self:provider.environment.BUCKET}
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
