service: dataeng-futures-wh-process

package:
  individually: true

provider:
  name: aws
  runtime: python3.7
  tracing:
    lambda: true
  environment:
    TEAM_HANDLER: src/handler/process_team_futures.process_team_futures
    PLAYER_HANDLER: src/handler/process_player_futures.process_player_futures
    MAP_PLAYERS_HANDLER: src/handler/map_players.map_players

    BOOKID: 'wh:book:whnj'
    STAGE: ${opt:stage, self:provider.stage}
    BUCKET: 'dataeng-futures-wh-ingest-${self:service}-${opt:stage, self:provider.stage}'
    DOC_DB_CONNECTION_STRING:  ${file(./config/config-${opt:stage, self:provider.stage}.yml):docDbConnectionString}
    LEAGUE_MONGO_COLLECTION: 'league_team_futures_wh'
    TEAM_MONGO_COLLECTION: 'team_futures_wh'
    PLAYER_MONGO_COLLECTION: 'player_futures_wh'
    LEAGUE_PLAYER_MONGO_COLLECTION: 'league_player_futures_wh'

    # RDS
    MYSQL_HOST: ${file(./config/config-${opt:stage, self:provider.stage}.yml):mysqlHost}
    MYSQL_USER: ${file(./config/config-${opt:stage, self:provider.stage}.yml):mysqlUser}
    MYSQL_PWD: ${file(./config/config-${opt:stage, self:provider.stage}.yml):mysqlPwd}
    MYSQL_DB: ${file(./config/config-${opt:stage, self:provider.stage}.yml):mysqlDb}

    PYMONGO_LAYER: ${file(./config/config-${opt:stage, self:provider.stage}.yml):pymongo-layer}
  stage: ${opt:stage, 'qa'}
  region: us-east-1
  timeout: 60
  vpc: ${file(./config/config-${opt:stage, self:provider.stage}.yml):vpc}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:provider.environment.BUCKET}/*'

functions:
  # NFL
  nfl_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nfl'
        CBS_LEAGUE_ID: 59
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NBA
  nba_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nba'
        CBS_LEAGUE_ID: 54
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-nba-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-nba-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # MLB
  mlb_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'mlb'
        CBS_LEAGUE_ID: 52
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-mlb-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-mlb-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NCAAF
  ncaaf_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'ncaaf'
        CBS_LEAGUE_ID: 56
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-ncaaf-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-ncaaf-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # NCAAB
  ncaab_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'ncaab'
        CBS_LEAGUE_ID: 55
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-ncaab-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-ncaab-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}
  # nhl
  nhl_team:
    handler: ${self:provider.environment.TEAM_HANDLER}
    environment:
        LEAGUE: 'nhl'
        CBS_LEAGUE_ID: 60
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-nhl-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-nhl-topic-${opt:stage, self:provider.stage}'
    layers:
      - ${self:provider.environment.PYMONGO_LAYER}

  # NFL players
  nfl_player:
    handler: ${self:provider.environment.PLAYER_HANDLER}
    environment:
      LEAGUE: 'nfl'
      CBS_LEAGUE_ID: 59
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'

    layers:
      - ${self:provider.environment.PYMONGO_LAYER}

  # MAP NFL players
  map_nfl_players:
    handler: ${self:provider.environment.MAP_PLAYERS_HANDLER}
    environment:
      LEAGUE: 'nfl'
      CBS_LEAGUE_ID: 59
    events:
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'
          topicName: 'dataeng-wh-futures-ingest-nfl-topic-${opt:stage, self:provider.stage}'


plugins:
  - serverless-python-requirements
