vpc:
  subnetIds:
    - subnet-0154f6ee3620b9ffb
    - subnet-0420dc1346cfd3b35
    - subnet-09ca40955bc02ef4c
  securityGroupIds:
    - sg-0a19f4a2ae5462222

docDbConnectionString:
  mongodb://atlas_write:NmBv56U874Esd9@datatech-sdf-docdb-prod:cluster-cor1sgl3m5gj:us-east-1:docdb:amazonaws:com:27017/atlas?w=1&replicaSet=rs0&readPreference=secondaryPreferred&authSource=admin&retryWrites=false&ssl=true

mysqlHost:
  cbss-sdf-prod-atlas-enc.cluster-cvrvcmdwbquf.us-east-1.rds.amazonaws.com
mysqlUser:
  atlas_write
mysqlPwd:
  719l0uc6Z2zb
mysqlDb:
  atlas

pymongo-layer:
  arn:aws:lambda:us-east-1:104016028232:layer:pymongo:1
