vpc:
    subnetIds:
      - subnet-0154f6ee3620b9ffb
      - subnet-0420dc1346cfd3b35
      - subnet-09ca40955bc02ef4c
    securityGroupIds:
      - sg-0a19f4a2ae5462222

docDbConnectionString:
  mongodb://atlas_write:weakWriteQA@datatech-sdf-docdb-qa.cluster-c5q8zvl01dua.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
